### ISSUE TITLE
Queue & Threads

### ISSUE THREAD

**Issue by Pablo2m** [heynemann/cyrusbus#1]
Hi
I'm trying to use queue to send information to a thread then use to feed cyrusbus. Could you add some kind bus.queue function ("queue_name", command = foo = bar options)?
  In the thread I have among other things, these lines

```
    if run_queue.empty ():
        sleep (1)
    else:
        run_queue.get take = ()
        bus.publish (cmd = take [0], opt = take [1])
```

Do you know any better solution?

**Comment by heynemann** [comment]
Hmm... I don't quite understand what you are doing. I think I need more information. The code above looks like it works. Not sure, though.

**Comment by Pablo2m** [comment]
Maybe its my english. Can you read spanish? I read portuguese...

**Comment by heynemann** [comment]
I can't read proper spanish. Try it, though. I'll translate in google if it helps.

**Comment by Pablo2m** [comment]
Bueno este es el problema:
Tengo dos threads, el el principal corre wxpython y en el auxiliar otra librería con otro bucle infinito. La única forma de lograr que el thread principal pueda mandar un evento al auxiliar que conozco es usar un queue y luego reconstruyéndolo con el código que te copie en el mensaje anterior.
Quería saber si se te ocurre una solución mejor y si no  ¿podrías  implementar una función extra en cyrus bus para crear el queue ? tengo que usar unos 20 queue y creo que el código se vería y entendería  mejor si los creara con una llamada a cyrus bus.
Espero haberme explicado mejor,  si no por favor pregunta

**Comment by heynemann** [comment]
Você pode implementar esta função no cyrusbus e mandar um pull request aqui no github pra eu ter uma idéia melhor do que é?

Obrigado
